version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - mysql

  mysql:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  proxy:
    build: ./proxy_keycloak/proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - keycloak

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  mysql-data:
