version: '3.1'

services:
  mysql:
    build: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
